name: Build & Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node env
        uses: actions/setup-node@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Test and build
        run: |
          npm ci
          npm run build
